apiVersion: apps/v1
kind: Deployment
metadata:
  name: trapezius
  labels:
    app: trapezius
spec:
  replicas: 3
  selector:
    matchLabels:
      app: trapezius
  template:
    metadata:
      labels:
        app: trapezius
    spec:
      containers:
      - name: trapezius
        image: hiromumasuda/trapezius:arm
        ports:
          - containerPort: 9090
---
apiVersion: v1
kind: Service
metadata:
  name: trapezius
spec:
  selector:
    app: trapezius
  type: NodePort
  ports:
    - protocol: TCP
      targetPort: 9090
      port: 9090
      nodePort: 30008
